title: Thelma Selase Akama
logo: assets/Profile Pic.png
About me: I am a Financial Data Analyst who applies statistical and quantitative methods to solve complex problems in finance and risk. I specialize in credit risk modelling, time-series forecasting, and financial analytics using Python and SQL to drive clear, data-backed decisions.

My work focuses on turning raw financial data into actionable insight, building robust models, and asking the right questions that inform strategyâ€”not just reports. This portfolio reflects my commitment to rigor, impact, and continuous growth toward high-level roles in fintech, investment, and financial services.
show_downloads: FALSE
theme: jekyll-theme-minimal
Education and Certifications: 
Work Experiences/Projects: 
Core Competencies:
